fix: wrong `dgram` compatibility info
denoland/deno-docs pull request #150
Opened 2023-09-27 10:03 UTC by hey-ab

That PR fix wrong compatibility info about `node:dgram`. In fact, the realization is quite partial and most popular libraries using `dgram` not working in Deno.
Proof: https://github.com/denoland/deno/issues/18324#issuecomment-1478034481
Some issues with `dgram`: https://github.com/denoland/deno/issues?q=dgram

2023-09-27 10:37 UTC, hey-ab commented
My mistake, see https://github.com/denoland/deno/issues/18324#issuecomment-1737141836

2023-10-02 14:23 UTC, kwhinnery requested changes

2023-10-02 14:23 UTC, kwhinnery commented on runtime/manual/node/compatibility.mdx
> +    Much of the dgram module internals is yet to be implemented.
```suggestion
```

2023-10-02 14:23 UTC, kwhinnery commented on runtime/manual/node/compatibility.mdx
> +    Some <code>dgram.Socket</code> instance methods is non-functional stubs:
```suggestion
    Some <code>dgram.Socket</code> instance methods are non-functional stubs:
```

2023-10-02 14:24 UTC, kwhinnery commented
Thanks for this @hey-ab - made a few suggestions. I will go ahead and commit them unless you object, and merge this in the next ~day or so unless I hear from you. Thanks again!

2023-10-02 16:32 UTC, merged