Deploy onboarding docs
denoland/deno-docs pull request #363
Opened 2024-03-13 11:07 UTC by thisisjofrank

2024-03-13 11:09 UTC, thisisjofrank commented
merging should be blocked until new onboarding flow goes live

2024-03-14 15:25 UTC, donjo requested changes
left a few notes, thanks for taking this up!

2024-03-15 11:26 UTC, thisisjofrank commented on deploy/manual/index.mdx
> +3. Complete the Project Configuration form. This will create a GitHub action to deploy your project. Give your project a name and select from the optional framework presets. If you are not using a fr
I've updated the copy, let me know if you think it needs to be more explicit re - if you've not got a built step

2024-03-15 13:18 UTC, donjo approved these changes
lgtm

2024-03-21 14:16 UTC, merged